return {
  meta = {
    id = "stt_unit_visual_board_v2_contract",
    plugin = "stt",
    type = "unit",
    title = "视觉画板 v2 规范化 spellID、文本对齐与层级契约",
  },
  init = {
    spellTextureMap = {
      [1253031] = "Interface\\Icons\\Spell_Seed_1253031",
    },
  },
  events = {
    {
      type = "visual_board_v2_contract",
      render = true,
    },
  },
  expect = {
    equals = {
      illegalShapeKind = "rect",
      shapeSwitchCircleKind = "circle",
      shapeSwitchCircleRadius = 60,
      shapeSwitchCircleEndX = nil,
      shapeSwitchArrowKind = "arrow",
      shapeSwitchArrowEndX = 520,
      shapeSwitchArrowEndY = 100,
      shapeSwitchArrowThickness = 3,
      shapeSwitchArrowSize = 22,
      spacePanSelectCount = 0,
      spacePanDragCount = 0,
      spacePanBackgroundCount = 0,
      normalSelectCount = 2,
      normalDragCount = 1,
      normalBackgroundCount = 1,
      editorSpaceWhileDown = true,
      editorSpaceAfterRelease = false,
      shortcutSpacePropagates = false,
      shortcutSpaceKeyUpPropagates = true,
      shortcutCommandXPropagates = false,
      shortcutCommandXDeleted = true,
      shortcutCommandCopyConsumed = true,
      shortcutCommandPasteConsumed = true,
      shortcutPasteCreated = true,
      iconSpellID = 1253031,
      iconTexture = nil,
      iconAtlas = nil,
      iconShape = "circle",
      personSpellID = 1253031,
      personTexture = nil,
      personIconShape = "square",
      circleZ = 1,
      personZ = 2,
      fontJustify = {
        { text = "P1", justifyH = "RIGHT", width = 16 },
        { text = "左对齐", justifyH = "LEFT", width = 120 },
      },
      renderedTextures = {
        first = "Interface\\AddOns\\ShengTangTools\\media\\visual_board\\slot_circle.tga",
        second = "Interface\\Icons\\Spell_Seed_1253031",
        third = "Interface\\Icons\\Spell_Seed_1253031",
      },
      renderedMasks = {
        first = 0,
        second = 0,
        third = 1,
      },
      frameGeometry = {
        slide1Hit = { point = "CENTER", relPoint = "TOPLEFT", x = 100, y = -100 },
        slide2Hit = { point = "CENTER", relPoint = "TOPLEFT", x = 300, y = -220 },
        slide2Selection = { point = "CENTER", relPoint = "TOPLEFT", x = 300, y = -220 },
        slide2Rotation = { point = "CENTER", relPoint = "TOPLEFT", x = 300, y = -181.5 },
        slide2Geometry = { x = 300, y = 220, scale = 1 },
      },
    },
  },
}
