return {
  meta = {
    id = "stt_unit_export_import_import_settings_replace",
    plugin = "stt",
    type = "unit",
    title = "设置替换导入",
  },
  init = {
    now = 1711180200,
    playerName = "Tester",
    exportImport = {
      settings = {
        ttsVolume = 80,
        ["screenReminder.enabled"] = false,
        customAudioEnabled = false,
        customAudioPack = "OtherPack",
        ["castRecorder.backendEnabled"] = true,
        ["castRecorder.maxRecords"] = 4,
        ["castRecorder.showInGantt"] = false,
        ["dreadElegy.enabled"] = true,
        ["dreadElegy.lurabuttonsMVP"] = true,
        ["dreadElegy.lurabuttonsMVPZoneOnly"] = false,
        ["dreadElegy.lurabuttonsMVPEncounterOnly"] = true,
        ["dreadElegy.raidOnly"] = false,
        ["dreadElegy.runeRouteMode"] = "sequential",
        ["dreadElegy.announceNumberOnShow"] = true,
        ["dreadElegy.panelOpacity"] = 50,
        ["dreadElegy.autoHideSeconds"] = 15,
        ["dreadElegy.chatType"] = "say",
        ["luraCrystal.enabled"] = true,
        ["luraCrystal.indicatorName"] = "文本#2",
        ["luraCrystal.durationSec"] = 4.5,
        ["luraCrystal.countdownAudioEnabled"] = false,
        ["auraColorAlert.enabled"] = true,
        ["auraColorAlert.pulse"] = false,
        ["auraColorAlert.showName"] = false,
        ["auraColorAlert.audioEnabled"] = true,
        ["auraColorAlert.scale"] = 1.4,
        ["auraColorAlert.alpha"] = 0.5,
        ["auraColorAlert.pos.point"] = "CENTER",
        ["auraColorAlert.pos.relPoint"] = "CENTER",
        ["auraColorAlert.pos.x"] = 10,
        ["auraColorAlert.pos.y"] = -20,
        ["semanticTimeline.ui.enabled"] = true,
        ["semanticTimeline.ui.durationBarHeight"] = 8,
        ["tacticTranslator.enabled"] = true,
        tacticTranslatorFormat = "mrt",
        tacticTranslatorMRTBoss = 3183,
        ["interruptRotation.uiStyle"] = "text",
        ["interruptRotation.bossEnabled.3183"] = false,
        unknownFutureSetting = true,
      },
    },
  },
  events = {
    { type = "export_import_export", channel = "settings" },
    {
      type = "export_import_reseed",
      state = {
        settings = {
          ttsVolume = 55,
          ["screenReminder.enabled"] = true,
          customAudioEnabled = true,
          customAudioPack = "ShengTangTools",
          ["castRecorder.backendEnabled"] = false,
          ["castRecorder.maxRecords"] = 1,
          ["castRecorder.showInGantt"] = true,
          ["dreadElegy.enabled"] = false,
          ["dreadElegy.lurabuttonsMVP"] = false,
          ["dreadElegy.lurabuttonsMVPZoneOnly"] = true,
          ["dreadElegy.lurabuttonsMVPEncounterOnly"] = false,
          ["dreadElegy.raidOnly"] = true,
          ["dreadElegy.runeRouteMode"] = "event",
          ["dreadElegy.announceNumberOnShow"] = false,
          ["dreadElegy.panelOpacity"] = 85,
          ["dreadElegy.autoHideSeconds"] = 10,
          ["dreadElegy.chatType"] = "raid",
          ["luraCrystal.enabled"] = false,
          ["luraCrystal.indicatorName"] = "计时条#1",
          ["luraCrystal.durationSec"] = 3,
          ["luraCrystal.countdownAudioEnabled"] = true,
          ["auraColorAlert.enabled"] = false,
          ["auraColorAlert.pulse"] = true,
          ["auraColorAlert.showName"] = true,
          ["auraColorAlert.audioEnabled"] = false,
          ["auraColorAlert.scale"] = 1,
          ["auraColorAlert.alpha"] = 1,
          ["auraColorAlert.pos.point"] = "TOP",
          ["auraColorAlert.pos.relPoint"] = "TOP",
          ["auraColorAlert.pos.x"] = 0,
          ["auraColorAlert.pos.y"] = -100,
          ["semanticTimeline.ui.enabled"] = false,
          ["semanticTimeline.ui.durationBarHeight"] = 6,
          ["tacticTranslator.enabled"] = false,
          tacticTranslatorFormat = "nsrt",
          tacticTranslatorMRTBoss = 0,
          ["interruptRotation.uiStyle"] = "banner",
          ["interruptRotation.bossEnabled.3183"] = true,
          ["auraColorAlert.pos.extra"] = "remove-me",
          unknownFutureSetting = "remove-me",
        },
      },
    },
    {
      type = "export_import_import",
      mode = "replace",
      source = "last",
      collectState = {
        settingsPaths = {
          "ttsVolume",
          "screenReminder.enabled",
          "customAudioEnabled",
          "customAudioPack",
          "castRecorder.backendEnabled",
          "castRecorder.maxRecords",
          "castRecorder.showInGantt",
          "dreadElegy.enabled",
          "dreadElegy.lurabuttonsMVP",
          "dreadElegy.lurabuttonsMVPZoneOnly",
          "dreadElegy.lurabuttonsMVPEncounterOnly",
          "dreadElegy.raidOnly",
          "dreadElegy.runeRouteMode",
          "dreadElegy.announceNumberOnShow",
          "dreadElegy.panelOpacity",
          "dreadElegy.autoHideSeconds",
          "dreadElegy.chatType",
          "luraCrystal.enabled",
          "luraCrystal.indicatorName",
          "luraCrystal.durationSec",
          "luraCrystal.countdownAudioEnabled",
          "auraColorAlert.enabled",
          "auraColorAlert.pulse",
          "auraColorAlert.showName",
          "auraColorAlert.audioEnabled",
          "auraColorAlert.scale",
          "auraColorAlert.alpha",
          "auraColorAlert.pos.point",
          "auraColorAlert.pos.relPoint",
          "auraColorAlert.pos.x",
          "auraColorAlert.pos.y",
          "semanticTimeline.ui.enabled",
          "semanticTimeline.ui.durationBarHeight",
          "tacticTranslator.enabled",
          "tacticTranslatorFormat",
          "tacticTranslatorMRTBoss",
          "interruptRotation.uiStyle",
          "interruptRotation.bossEnabled.3183",
          "auraColorAlert.pos.extra",
          "unknownFutureSetting",
        },
      },
    },
  },
  expect = {
    equals = {
      ok = true,
      message = "设置导入完成：已应用 38 项，跳过 0 项",
      reloadUICount = 0,
      snapshot = {
        semantic = {},
        personal = {},
        settings = {
          ["ttsVolume"] = 80,
          ["screenReminder.enabled"] = false,
          customAudioEnabled = false,
          customAudioPack = "OtherPack",
          ["castRecorder.backendEnabled"] = true,
          ["castRecorder.maxRecords"] = 4,
          ["castRecorder.showInGantt"] = false,
          ["dreadElegy.enabled"] = true,
          ["dreadElegy.lurabuttonsMVP"] = true,
          ["dreadElegy.lurabuttonsMVPZoneOnly"] = false,
          ["dreadElegy.lurabuttonsMVPEncounterOnly"] = true,
          ["dreadElegy.raidOnly"] = false,
          ["dreadElegy.runeRouteMode"] = "sequential",
          ["dreadElegy.announceNumberOnShow"] = true,
          ["dreadElegy.panelOpacity"] = 50,
          ["dreadElegy.autoHideSeconds"] = 15,
          ["dreadElegy.chatType"] = "say",
          ["luraCrystal.enabled"] = true,
          ["luraCrystal.indicatorName"] = "文本#2",
          ["luraCrystal.durationSec"] = 4.5,
          ["luraCrystal.countdownAudioEnabled"] = false,
          ["auraColorAlert.enabled"] = true,
          ["auraColorAlert.pulse"] = false,
          ["auraColorAlert.showName"] = false,
          ["auraColorAlert.audioEnabled"] = true,
          ["auraColorAlert.scale"] = 1.4,
          ["auraColorAlert.alpha"] = 0.5,
          ["auraColorAlert.pos.point"] = "CENTER",
          ["auraColorAlert.pos.relPoint"] = "CENTER",
          ["auraColorAlert.pos.x"] = 10,
          ["auraColorAlert.pos.y"] = -20,
          ["semanticTimeline.ui.enabled"] = true,
          ["semanticTimeline.ui.durationBarHeight"] = 8,
          ["tacticTranslator.enabled"] = true,
          tacticTranslatorFormat = "mrt",
          tacticTranslatorMRTBoss = 3183,
          ["interruptRotation.uiStyle"] = "text",
          ["interruptRotation.bossEnabled.3183"] = false,
          ["auraColorAlert.pos.extra"] = nil,
          unknownFutureSetting = nil,
        },
      },
    },
  },
}
