return {
  meta = {
    id = "stt_unit_export_import_export_settings",
    plugin = "stt",
    type = "unit",
    title = "导出设置仅包含差异项",
  },
  init = {
    now = 1711180200,
    playerName = "Tester",
    exportImport = {
      settings = {
        ttsVolume = 80,
        ["screenReminder.enabled"] = false,
        customAudioEnabled = false,
        customAudioPack = "OtherPack",
        ["castRecorder.backendEnabled"] = true,
        ["castRecorder.maxRecords"] = 4,
        ["castRecorder.showInGantt"] = false,
        ["dreadElegy.enabled"] = true,
        ["dreadElegy.lurabuttonsMVP"] = true,
        ["dreadElegy.lurabuttonsMVPZoneOnly"] = false,
        ["dreadElegy.lurabuttonsMVPEncounterOnly"] = true,
        ["dreadElegy.raidOnly"] = false,
        ["dreadElegy.runeRouteMode"] = "sequential",
        ["dreadElegy.announceNumberOnShow"] = true,
        ["dreadElegy.panelOpacity"] = 50,
        ["dreadElegy.autoHideSeconds"] = 15,
        ["dreadElegy.chatType"] = "say",
        ["luraCrystal.enabled"] = true,
        ["luraCrystal.indicatorName"] = "文本#2",
        ["luraCrystal.durationSec"] = 4.5,
        ["luraCrystal.countdownAudioEnabled"] = false,
        ["auraColorAlert.enabled"] = true,
        ["auraColorAlert.pulse"] = false,
        ["auraColorAlert.showName"] = false,
        ["auraColorAlert.audioEnabled"] = true,
        ["auraColorAlert.scale"] = 1.4,
        ["auraColorAlert.alpha"] = 0.5,
        ["auraColorAlert.pos.point"] = "CENTER",
        ["auraColorAlert.pos.relPoint"] = "CENTER",
        ["auraColorAlert.pos.x"] = 10,
        ["auraColorAlert.pos.y"] = -20,
        ["semanticTimeline.ui.enabled"] = true,
        ["semanticTimeline.ui.durationBarHeight"] = 8,
        ["tacticTranslator.enabled"] = true,
        tacticTranslatorFormat = "mrt",
        tacticTranslatorMRTBoss = 3183,
        ["interruptRotation.uiStyle"] = "text",
        ["interruptRotation.bossEnabled.3183"] = false,
        unknownFutureSetting = true,
        ["semanticTimeline.notes.sample"] = "skip-me",
      },
    },
  },
  events = {
    { type = "export_import_export", channel = "settings" },
  },
  expect = {
    equals = {
      ok = true,
      prefix = "STT:1:S:",
      hasText = true,
      summary = {
        typeCode = "S",
        typeName = "设置配置",
        version = 1,
        exportTime = 1711180200,
        exporterName = "Tester",
        exporterVersion = "260323.25",
        planCount = 0,
        personalPlanCount = 0,
        settingsCount = 38,
      },
    },
  },
}
