return {
  meta = {
    id = "stt_unit_semantic_boss_sync_visual_board_package",
    plugin = "stt",
    type = "unit",
    title = "语义 Boss 同步携带并覆盖导入当前 Boss 完整视觉画板包",
  },
  init = {
    inRaid = false,
    playerName = "Leader",
  },
  events = {
    {
      type = "semantic_boss_visual_board_package_sync",
    },
  },
  expect = {
    equals = {
      coldEditorLoadedCaptured = true,
      buildBossManifestRuntime = "function",
      buildBossDeltaRuntime = "function",
      applyBossManifestRuntime = "function",
      mergeBossDeltaRuntime = "function",
      sameSendCount = 1,
      samePackageMode = "manifest",
      sentProto = "S2",
      packageBossKey = "raid:1308:3183",
      packageMode = "manifest",
      packageCount = 9,
      packageHasFullElements = false,
      packagePrio = "NORMAL",
      deltaSentProto = "S2B",
      deltaPackageMode = "delta",
      deltaPackageCount = 1,
      deltaSyncKeys = { "sync-5" },
      deltaHasOtherBoss = false,
      deltaHasFullElements = true,
      deltaPrio = "NORMAL",
      deltaTimeout = 60,
      deltaMaxRetries = 0,
      receivedPlanID = 501,
      activePlanID = 501,
      activeContextKey = "boss:raid:1308:3183",
      manifestMatched = 2,
      manifestMissingCount = 7,
      manifestRemoved = 0,
      manifestPendingRemoved = 1,
      manifestBossCount = 3,
      oldCurrentRemoved = false,
      deltaMergeRemoved = 1,
      deltaMergedBossCount = 3,
      oldCurrentRemovedAfterDelta = true,
      otherBossCount = 1,
      otherBossNames = { "其它Boss保留" },
      emptyHasPackage = false,
    },
  },
}
