return {
  meta = {
    id = "stt_unit_runtime_boss_plan_ssot_no_active_fallback",
    plugin = "stt",
    type = "unit",
    title = "显式Boss运行时只读取本Boss方案且不回退激活方案",
  },
  events = {
    {
      type = "runtime_boss_plan_ssot",
      bossKey = "raid:1308:3182",
      oldBossKey = "raid:1308:3183",
      activeText = "{time:00:08} M8旧方案",
      emptyBossText = "",
    },
  },
  expect = {
    equals = {
      explicitAbsent = {
        source = "STN",
        hasText = false,
        text = "",
        fallbackActive = false,
        teamPlanIDPresent = false,
        personalPlanIDPresent = false,
        activePlanIDPresent = false,
        currentBossKey = "raid:1308:3183",
        bundleBossKey = "raid:1308:3182",
      },
      afterSuppressedSyncSwitch = {
        source = "STN",
        hasText = true,
        text = table.concat({
          "[方案]",
          "名称 = 未命名Boss",
          "作者 = STT",
          "",
          "[人员]",
          "",
          "[时间轴]",
          "{time:00:08} M8旧方案",
        }, "\n"),
        fallbackActive = false,
        teamPlanIDPresent = true,
        personalPlanIDPresent = false,
        activePlanIDPresent = false,
        currentBossKey = "raid:1308:3183",
        bundleBossKey = "raid:1308:3183",
      },
      afterWorkbenchSwitch = {
        source = "STN",
        hasText = false,
        text = "",
        fallbackActive = false,
        teamPlanIDPresent = false,
        personalPlanIDPresent = false,
        activePlanIDPresent = false,
        currentBossKey = "raid:1308:3182",
        bundleBossKey = "raid:1308:3182",
      },
      empty = {
        source = "STN",
        hasText = false,
        text = "",
        fallbackActive = false,
        teamPlanIDPresent = true,
        personalPlanIDPresent = false,
        activePlanIDPresent = false,
        currentBossKey = "raid:1308:3182",
        bundleBossKey = "raid:1308:3182",
      },
      afterEncounterStart = {
        source = "STN",
        hasText = false,
        text = "",
        fallbackActive = false,
        teamPlanIDPresent = true,
        personalPlanIDPresent = false,
        activePlanIDPresent = false,
        currentBossKey = "raid:1308:3182",
        bundleBossKey = "raid:1308:3182",
      },
    },
  },
}
